execute at @s unless entity @s[hasitem={item=gabrielaplok:silencer, location=slot.inventory, slot=2}] run playsound effect.gun.echo @a[r=50] ~~~ 100 1 0.01

execute at @s unless entity @s[hasitem={item=gabrielaplok:silencer, location=slot.inventory, slot=2}] run execute as @s[hasitem={item=gabrielaplok:ak47, location=slot.weapon.mainhand}] run playsound effect.gun.dist.low @a[rm=2, r=400] ~~~ 200 1 1
execute at @s unless entity @s[hasitem={item=gabrielaplok:silencer, location=slot.inventory, slot=2}] run execute as @s[hasitem={item=gabrielaplok:awp, location=slot.weapon.mainhand}] run playsound effect.gun.dist.large @a[rm=2, r=400] ~~~ 200 1 1
execute at @s unless entity @s[hasitem={item=gabrielaplok:silencer, location=slot.inventory, slot=2}] run execute as @s[hasitem={item=gabrielaplok:desert_eagle, location=slot.weapon.mainhand}] run playsound effect.gun.dist.short @a[rm=2, r=400] ~~~ 200 1 1
execute at @s unless entity @s[hasitem={item=gabrielaplok:silencer, location=slot.inventory, slot=2}] run execute as @s[hasitem={item=gabrielaplok:fnfal, location=slot.weapon.mainhand}] run playsound effect.gun.dist.low @a[rm=2, r=400] ~~~ 200 1 1
execute at @s unless entity @s[hasitem={item=gabrielaplok:silencer, location=slot.inventory, slot=2}] run execute as @s[hasitem={item=gabrielaplok:glock17, location=slot.weapon.mainhand}] run playsound effect.gun.dist.short @a[rm=2, r=400] ~~~ 200 1 1
execute at @s unless entity @s[hasitem={item=gabrielaplok:silencer, location=slot.inventory, slot=2}] run execute as @s[hasitem={item=gabrielaplok:glock18, location=slot.weapon.mainhand}] run playsound effect.gun.dist.short @a[rm=2, r=400] ~~~ 200 1 1
execute at @s unless entity @s[hasitem={item=gabrielaplok:silencer, location=slot.inventory, slot=2}] run execute as @s[hasitem={item=gabrielaplok:m4a1, location=slot.weapon.mainhand}] run playsound effect.gun.dist.medium @a[rm=2, r=400] ~~~ 200 1 1
execute at @s unless entity @s[hasitem={item=gabrielaplok:silencer, location=slot.inventory, slot=2}] run execute as @s[hasitem={item=gabrielaplok:mossberg, location=slot.weapon.mainhand}] run playsound effect.gun.dist.large_extra @a[rm=2, r=400] ~~~ 200 1 1
execute at @s unless entity @s[hasitem={item=gabrielaplok:silencer, location=slot.inventory, slot=2}] run execute as @s[hasitem={item=gabrielaplok:mossberg, location=slot.weapon.mainhand}] run playsound effect.gun.dist.short @a[rm=2, r=400] ~~~ 200 1 1